config/routes.rb
Rails.application.routes.draw do

  resources :cake_sizes
  resources :users
  resources :cake_styles do
    collection do
      get 'all'
      get 'current'
    end
  end
  resources :locations
  resources :orders do
  	resources :comments
    collection do
      get 'search'
    end
    member do
      patch 'cancel_switch'
    end
  end
  
  get '/daily_orders', to: 'orders#daily_orders', as: :daily_orders
  get '/daily_messages', to: 'orders#daily_messages', as: :daily_messages
  get '/login', to: 'access#login', as: :login
  post '/attempt_login', to: 'access#attempt_login', as: :attempt_login
  get '/admin_panel', to: 'access#admin_panel', as: :admin_panel
  get '/logout', to: 'access#logout', as: :logout
  root 'access#admin_panel'

 
end

app/models/cake_style.rb
class CakeStyle < ActiveRecord::Base
	has_many :orders, inverse_of: :cake_style

	has_attached_file :style_photo, styles: { original: "500x500>", medium: "300x300>", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :style_photo, content_type: /\Aimage\/.*\Z/

  	scope :current_styles, -> { where("current = ?", true) }

  	scope :recent, -> { order(created_at: :desc)}

	def has_orders?
		orders.any?
	end


private



end

app/controllers/cake_styles_controller.rb
class CakeStylesController < ApplicationController
  before_action :allow_admin, only: [ :destroy]
  before_action :set_cake_style, only: [:show, :edit, :update, :destroy]
  before_action :load_objects

  
  def index
    @cake_styles = CakeStyle.recent
  end

  def current
    @cake_styles = CakeStyle.current_styles
  end

  # GET /cake_styles/1
  # GET /cake_styles/1.json
  def show
    @upcoming_style_orders = CakeStyle.find(params[:id]).orders.sorted.upcoming
    @orders = @upcoming_style_orders
  end

  # GET /cake_styles/new
  def new
    @cake_style = CakeStyle.new
  end

  # GET /cake_styles/1/edit
  def edit
  end

  # POST /cake_styles
  # POST /cake_styles.json
  def create
    @cake_style = CakeStyle.new(cake_style_params)
      if @cake_style.save
        redirect_to @cake_style, notice: 'Cake style was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /cake_styles/1
  # PATCH/PUT /cake_styles/1.json
  def update
      if @cake_style.update(cake_style_params)
        redirect_to @cake_style, notice: 'Cake style was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /cake_styles/1
  # DELETE /cake_styles/1.json
  def destroy
    if @cake_style.has_orders?
      redirect_to @cake_style, notice: 'Cannot destroy Cake Styles with Orders'
    else
      if @cake_style.destroy 
        redirect_to cake_styles_url, notice: 'Cake style was successfully destroyed.'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cake_style
      @cake_style = CakeStyle.find(params[:id])
    end

    def load_objects
      @cake_sizes = CakeSize.all
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cake_style_params
      params.require(:cake_style).permit(:name, :description, :current, :style_photo)
    end
end

app/helpers/cake_styles_helper.rb
module CakeStylesHelper
end

app/views/cake_styles/_cake_style.html.erb
<div class="cake-list-item">
  <div class="cakephoto">
    <%= link_to image_tag(cake_style.style_photo.url(:thumb)), cake_style_path(cake_style.id) %>
  </div>
  <div class="cake-info">
    <%= link_to cake_style.name, cake_style_path(cake_style.id), class: 'action' %>
    <p><%= cake_style.orders.upcoming.count %> UPCOMING</p>
    <p><%= cake_style.orders.pickup_on(Time.zone.today).count %> TODAY</p>
    <div class="actions">
      <%= link_to 'Order', new_order_path(cake_style_id: cake_style.id), class: 'action' %>
      <%= link_to 'Edit', edit_cake_style_path(cake_style), class: 'action' %>
    </div>
  </div>
</div>

app/views/cake_styles/_form.html.erb
<div class='form'>
<%= form_for(@cake_style) do |f| %>
  <% if @cake_style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cake_style.errors.count, "error") %> prohibited this cake_style from being saved:</h2>

      <ul>
      <% @cake_style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row 1'>
    <%= f.text_field :name, placeholder: 'Cake Style Name' %>
  </div>

  <div class='row 2'>
    <div>
      <%= f.label :current %>
      <%= f.check_box :current %>
    </div>
  </div>

  <div class='row 3'>
    <div class='column 1'>
      <%= f.label :style_photo, 'Photo' %><br>
      <%= @cake_style.style_photo.present? ? image_tag(@cake_style.style_photo.url(:medium)) : '' %>
      <%= f.file_field :style_photo %>
    </div>
    <div class='column 2'>
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'notes' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Save Cake Style', class: 'action' %>
    <%= link_to 'Destroy', @cake_style, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action' if @cake_style.persisted?  %>
  </div>
<% end %>
</div>

app/views/cake_styles/_subnav.html.erb
<nav class="subnav">
	<%= link_to "Current Styles", :current_cake_styles %>
	<%= link_to "All Styles", :cake_styles %>
	<%= link_to "New Style", :new_cake_style %>
</nav>

app/views/cake_styles/all.html.erb
<h2>All Cake Styles</h2>
<div class="cake-list">
  <%= render @cake_styles %>
</div>

app/views/cake_styles/current.html.erb
<h2>Current Cake Styles</h2>
<div class="cake-list">
  <%= render @cake_styles %>
</div>

app/views/cake_styles/edit.html.erb
<h1>Editing Cake Style</h1>

<%= render 'form' %>

app/views/cake_styles/index.html.erb
<h2>All Cake Styles</h2>
<div class="cake-list">
  <%= render @cake_styles %>
</div>

app/views/cake_styles/new.html.erb
<h1>New Cake Style</h1>

<%= render 'form' %>

app/views/cake_styles/show.html.erb
 <div class='form'>
 	<div class='row 1'>
	  <strong><%= content_tag(:h1, "#{@cake_style.name}") %></strong>
	</div>

	<div class='row 2'>
	  	<%= @cake_style.current ? 'CURRENT STYLE' : content_tag(:div, 'NOT CURRENT STYLE', class: 'status') %>
	</div>

	<div class='row 3'>
	  <div class='column 1'>
		<%= image_tag @cake_style.style_photo.url(:medium) %>
	  </div>
	  <div class='column 2'>
	  	<strong>Description:</strong>
	  	<%= @cake_style.description %>
	  </div>
	</div>

	<div class="row 4 actions">
	  <%= link_to 'Order', new_order_path(cake_style_id: @cake_style.id), class: 'action' %>
	  <%= link_to 'Edit', edit_cake_style_path(@cake_style), class: 'action' %>
	</div>
</div>

<h2>Upcoming Orders</h2>
<table>
<tr>
	<th>Pickup</th>
	<th>Date</th>
	<th>Time</th>
	<th>Style</th>
	<th>Size</td>
	<th>Message</th>
	<th>Notes</th>
	<th colspan="3"></th>
</tr>

<%= render partial: @orders %>
</table>