config/routes.rb
Rails.application.routes.draw do

  resources :cake_sizes
  resources :users
  resources :cake_styles do
    collection do
      get 'all'
      get 'current'
    end
  end
  resources :locations
  resources :orders do
  	resources :comments
    collection do
      get 'search'
    end
    member do
      patch 'cancel_switch'
    end
  end
  
  get '/daily_orders', to: 'orders#daily_orders', as: :daily_orders
  get '/daily_messages', to: 'orders#daily_messages', as: :daily_messages
  get '/login', to: 'access#login', as: :login
  post '/attempt_login', to: 'access#attempt_login', as: :attempt_login
  get '/admin_panel', to: 'access#admin_panel', as: :admin_panel
  get '/logout', to: 'access#logout', as: :logout
  root 'access#admin_panel'

 
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
before_action :allow_admin, except: [:login, :attempt_login, :logout]

def login
	
end

def attempt_login
	if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end
    if authorized_user
      # mark user as logged in
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      flash[:notice] = "You are now logged in."
      if authorized_user.admin
       redirect_to :admin_panel
      else
        redirect_to :orders
      end
    else
      flash[:notice] = "Invalid username/password combination."
      redirect_to :login
    end
	
end

def admin_panel
  
end

def logout
  session[:user_id] = nil
  session[:username] = nil
  flash[:notice] = "Logged out"
  redirect_to :login
end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/admin_panel.html.erb
<h1>Cacao Admin Panel</h1>


<div class="actions">
	<%= link_to 'LOCATIONS', locations_path, class: 'action' %>
	<%= link_to 'USERS', users_path, class: 'action' %>
	<%= link_to 'SIZES', cake_sizes_path, class: 'action' %>
	<%= link_to 'LOGOUT', :logout, class: 'action' %></div>
</div>

app/views/access/login.html.erb
<div class='column'>
	<%= form_tag action: :attempt_login do %>
		<%= text_field_tag :username, nil, placeholder: 'Username' %>
		<%= text_field_tag :password, nil, placeholder: 'Password' %>
		<%= submit_tag 'Login' %>
	<% end %>
</div>