config/routes.rb
Rails.application.routes.draw do

  resources :cake_sizes
  resources :users
  resources :cake_styles do
    collection do
      get 'all'
      get 'current'
    end
  end
  resources :locations
  resources :orders do
  	resources :comments
    collection do
      get 'search'
    end
    member do
      patch 'cancel_switch'
    end
  end
  
  get '/daily_orders', to: 'orders#daily_orders', as: :daily_orders
  get '/daily_messages', to: 'orders#daily_messages', as: :daily_messages
  get '/login', to: 'access#login', as: :login
  post '/attempt_login', to: 'access#attempt_login', as: :attempt_login
  get '/admin_panel', to: 'access#admin_panel', as: :admin_panel
  get '/logout', to: 'access#logout', as: :logout
  root 'access#admin_panel'

 
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :comments, dependent: :destroy

	#Associates a Location with an Order as the order_location.
	belongs_to :order_location, :class_name => 'Location', :foreign_key => 'order_location_id', inverse_of: :orders_at
	#Associates a Location with an Order as the pickup_location.
	belongs_to :pickup_location, :class_name => 'Location', :foreign_key => 'pickup_location_id', inverse_of: :pickups_at
	#Associates a CakeStyle with an Order.
	belongs_to :cake_style, inverse_of: :orders
	#Associates a User with an Order.
	belongs_to :user, inverse_of: :orders
	#Associates a CakeSize with an Order.
	belongs_to :cake_size, inverse_of: :orders

	has_attached_file :message_photo,
		styles: { original: "500x500>", medium: "300x300>", thumb: "150x150>" },
		convert_options: { },
		default_url: "/images/:style/missing.png"

  	validates_attachment_content_type :message_photo, content_type: /\Aimage\/.*\Z/

	validates :customer_name, :customer_phone, :cake_style, :cake_size_id, :order_location, :order_date, :user, :pickup_location, :pickup_date, :user_id, :price, :deposit, :balance, presence: true
	validates :cake_message, presence: true, length: { maximum: 32 }, if: 'message_photo.blank?'
	validates :message_photo, presence: true, if: 'cake_message.blank?'

	#validates :message, presence: true,
	#					length: { maximum: 30 }

	#scope :orders_today, ->  { where(:pickup_date => Time.zone.today)}
	#scope :orders_tomorrow, ->  { where(:pickup_date => Time.zone.tomorrow)}

	# List all orders, descending by pickup_date.
	scope :sorted, ->  { order(pickup_date: :desc) }

	# Choose pickup_date(s). Expects 1 argument in date format for requested day(s).
	scope :pickup_on, -> (pickup_date) { where("pickup_date = ?", pickup_date) }

	scope :by_style, -> { order(cake_style_id: :asc) }

	scope :by_size, -> { order(cake_size_id: :asc) }

	# List all orders, descending by most recently updated
	scope :recent, ->  { order(updated_at: :desc) }

	# List upcoming orders including today
	scope :upcoming, ->  { where("pickup_date >= ?", Time.zone.today) }


	scope :current_styles, ->  { joins(:cake_style).where("cake_styles.current = ?", true) }
	
	#Scopes included in search bar
	scope :uncurrent_styles, ->  { joins(:cake_style).where("cake_styles.current = ?", false) }
	scope :uncancelled, ->  { where("cancelled = ?", false) }
	scope :pickup_between, -> (pickup_start_date, pickup_end_date) { where("pickup_date >= ?", pickup_start_date).where("pickup_date <= ?", pickup_end_date) }
	scope :orders_at, -> (order_location_id) { where("order_location_id = ?", order_location_id)}
	scope :pickups_at, -> (pickup_location_id) { where("pickup_location_id = ?", pickup_location_id)}
	scope :ordered_by, -> (user_id) { where('user_id = ?', user_id) }
	scope :find_by_phone, -> (customer_phone) { where('customer_phone LIKE ?', "%#{customer_phone}%") }

	scope :cancelled, -> { where('cancelled = ?', true) }
					

end

#:customer, :phone, :order_date, :pickup_date, :price

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :allow_admin, only: [:destroy]
	before_action :load_select_objects


	def index
		@orders = Order.recent
		@orders_today = @orders.pickup_on(Time.zone.today)
		@orders_tomorrow = @orders.pickup_on(Time.zone.tomorrow)
		@recent_orders = @orders.recent
	end

	def show
		@order = Order.find(params[:id])
	end

	def new
		@order = Order.new({ cake_style_id: params[:cake_style_id] })
	end

	def create
		set_deposit_balance
		@order = Order.new(order_params)

		if @order.save
			redirect_to @order
		else
			render 'new'
		end
	end

	def edit
		@order = Order.find(params[:id])
		@cake_style = @order.cake_style
		@available_cake_styles << @cake_style
	end

	def update
		set_deposit_balance
		@order = Order.find(params[:id])

		if @order.update(order_params)
			redirect_to @order
		else
			render 'edit'
		end	
	end

	def destroy
		@order = Order.find(params[:id])
		if @order.cancelled
		  if @order.destroy
		  	redirect_to :orders, notice: 'Order was successfuly destroyed'
		  end
		else
			redirect_to @order, notice: 'Order must be cancelled before destroyed'
		end
	end

	def cancel_switch
		@order = Order.find(params[:id])
		switched_state = !@order.cancelled
		if @order.update(cancelled: switched_state)
			flash[:notice] = 'Order Updated Successfuly'
			redirect_back_or_default
		else
			flash[:notice] = 'Order Could Not Be Updated'
			redirect_back_or_default
		end	
		
	end

	def daily_orders
	   	if (params[:date]).present?
			@date = Date.parse(params[:date])
		else
			@date = Time.zone.today
		end
	    @orders = Order.pickup_on(@date).by_style.by_size
	end

	def daily_messages
		if (params[:date]).present?
			@date = Date.parse(params[:date])
		else
			@date = Time.zone.today
		end
	    @orders = Order.pickup_on(@date)
	end

	def search
		@orders = Order.recent
		if params[:uncurrent].present?
			@orders = @orders.uncurrent_styles
			@uncurrent_checked = true
		end
		if params[:uncancelled].present?
			@orders = @orders.uncancelled
			@uncancelled_checked = true
		end
		if params[:pickup_start_date].present? && params[:pickup_end_date].present?
			@pickup_start_date = params_date(:pickup_start_date)
			@pickup_end_date = params_date(:pickup_end_date)
			@orders = @orders.pickup_between(@pickup_start_date, @pickup_end_date)
		end
		if params[:order_location_id].present?
			@orders = @orders.orders_at(params[:order_location_id])
			@selected_order_location_id = params[:order_location_id]
		end
		if params[:pickup_location_id].present?
			@orders = @orders.pickups_at(params[:pickup_location_id])
			@selected_pickup_location_id = params[:pickup_location_id]
		end
		if params[:user_id].present?
			@orders = @orders.ordered_by(params[:user_id])
			@selected_user_id = params[:user_id]
		end
		if params[:customer_phone].present?
			@orders = @orders.find_by_phone(params[:customer_phone])
			@selected_customer_phone = params[:customer_phone]
		end
	end

private
	def order_params
		params.require(:order).permit(:customer_name, :customer_phone, :cake_style_id, :cake_size_id, :cake_message, :message_photo, :order_location_id, :order_date, :user_id, :pickup_location_id, :pickup_date, :pickup_time, :price, :deposit, :balance, :notes, :cancelled)
		
	end

	def load_select_objects
		@locations = Location.all
		@available_cake_styles = CakeStyle.current_styles
		@cake_sizes = CakeSize.all
		if params[:cake_style_id]
		@cake_style = CakeStyle.find(params[:cake_style_id])
		@available_cake_styles << @cake_style
		end
		@cake_style ||= @available_cake_styles.first
		@current_user = User.find(session[:user_id])
		@users = User.sorted.staff.located_at(@current_user.location_id)
	end

	def set_deposit_balance
		if params[:order][:deposit].empty?
			params[:order][:deposit] = params[:order][:price]
		end

		price = params[:order][:price].to_i
		deposit = params[:order][:deposit].to_i
		params[:order][:balance] = price - deposit
	end



end

app/helpers/orders_helper.rb
module OrdersHelper

	def cancel_switch(order)
		switched_state = order.cancelled ? 'RESTORE' : 'CANCEL'
		link_to "#{switched_state}", cancel_switch_order_path(order), method: 'patch', data: { confirm: 'Are you sure?' }, class: 'action'
	end

	def outstanding_balance?(order)
		order.balance > 0 ? content_tag(:div, "OUTSTANDING BALANCE  MOP#{order.balance}", class: 'status') : ''
	end

	def not_current_style?(order)
		order.cake_style.current ? '' : content_tag(:div, 'NOT CURRENT STYLE', class: 'status')
	end

	def cancelled?(order)
		order.cancelled ? content_tag(:div, 'CANCELLED', class: 'status') : ''
	end

	def pickup_link(order)
		link_to(order.pickup_location.name, location_path(order.pickup_location), class: 'action')
	end

	def cake_style_link(order)
		link_to(order.cake_style.name, cake_style_path(order.cake_style), class: 'action')
	end

end

app/views/orders/_form.html.erb
<div class='form'>
<%= form_for @order do |f| %>

 <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<div class='row 1'>
  <div class='column 1'>
    <div>
      <%= f.text_field :customer_name, placeholder: 'Customer' %>
    </div>
    <div>
      <%= f.text_field :customer_phone, placeholder: 'Phone' %>
    </div>
      <%= f.label '', 'Ordered By' %>
    <div>
      <%= f.grouped_collection_select :user_id, @locations, :staff, :name, :id, :username, prompt: 'Choose Staff' %>
    </div>
      <%= f.label 'Style' %>
    <div>
      <%= f.collection_select :cake_style_id, @available_cake_styles, :id, :name, selected: @cake_style.id %>
    </div>
      <%= f.label 'Size' %>
    <div>
      <%= f.collection_select :cake_size_id, @cake_sizes, :id, :name,  prompt: 'Choose Size' %>
    </div>
  </div>
  <div class='column 2'>
    <div>
      <%= f.text_field :cake_message, placeholder: 'Type Message or Choose File', maxlength: 32, size: 32 %>
    </div>
    <div>
      <%= f.file_field :message_photo %>
    </div>
    <div>
      <%= f.text_field :price, placeholder: 'Price' %>
    </div>
    <div>
      <%= f.text_area :deposit, placeholder: 'Deposit - Leave Blank If Paid In Full' %>
    </div>
  </div>
  <div class='column 3'>
    <div>
      <%= f.text_area :notes, placeholder: 'Notes - Leave Blank If Not Required', class: 'notes' %>
    </div>
    <div>
      <%= @order.cake_style.present? ? image_tag(@order.cake_style.style_photo.url(:thumb)) : '' %>
    </div>
  </div>
</div>

<div class='row 2'>
  <div>
    <%= f.label 'Ordered' %><br>
    <%= f.collection_select :order_location_id, @locations, :id, :name, selected: @current_user.location_id %>
    <%= f.date_select :order_date, start_year: 2016, end_year: 2026 %></br>
  </div>
  <div>
    <%= f.label 'Pickup' %><br>
    <%= f.collection_select :pickup_location_id, @locations, :id, :name, selected: @current_user.location_id %>
    <%= f.date_select :pickup_date, start_year: 2016, end_year: 2026, default: Time.zone.tomorrow %>
    <%= f.time_select :pickup_time, start_hour: 12, end_hour: 19, time_separator: ':', minute_step: 30, ampm: true, ignore_date: true %>
  </div>
</div>
<div class='row 3'>
  <%= f.submit class: 'action' %>
  <%= link_to 'Destroy', @order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action' if @order.persisted?  %>
</div>

<% end %>
</div>

app/views/orders/_order.html.erb
	<tr class="<%= order.cancelled ? 'cancelled' : cycle('odd', 'even') %>">
		<td><%= pickup_link(order) %></td>
		<td><%= order.pickup_date.strftime('%d/%m') %></td>
		<td><%= order.pickup_time.strftime('%l:%M%p') %></td>
		<td><%= cake_style_link(order) %></td>
		<td><%= order.cake_size.name %></td>
		<td><%= order.cake_message %></td>
		<td><%= order.notes %></td>
		<td><%= link_to 'Show', order_path(order), class: 'action' %></td>
		<td><%= link_to 'Edit', edit_order_path(order), class: 'action' %></td>
		<td><%= cancel_switch(order) %></td>
	 </tr>

app/views/orders/_search_bar.html.erb
<%= form_tag( :search_orders, method: :get, class: 'search-bar') do %>
	<div>
		<div>
			<%= label_tag :uncurrent, 'Hide Current Styles:' %>
			<%= check_box_tag :uncurrent, '1', @uncurrent_checked.present? %>
		</div>
		<div>
			<%= label_tag :uncancelled, 'Hide Cancelled Orders:' %>
			<%= check_box_tag :uncancelled, '1', @uncancelled_checked.present? %>
		</div>
		<div>
	 		<%= text_field_tag :customer_phone, @selected_customer_phone, placeholder: 'Customer Phone' %>
	 	</div>
	</div>
	<div>
		<div>
			<%= label_tag :pickup_date, 'Pickup Date:' %>
		</div>
		<div>
			<%= label_tag :pickup_start_date, 'From' %>
			<%= select_date @pickup_start_date || Time.zone.today, start_year: 2016, end_year: 2026, include_blank: :true, prefix: :pickup_start_date %>
		</div>
		<div>
			<%= label_tag :pickup_end_date, 'To' %>
			<%= select_date @pickup_end_date || Time.zone.today + 1.month, start_year: 2016, end_year: 2026, include_blank: :true, prefix: :pickup_end_date %>
		</div>
	</div>
	<div>
		<div>
			<%= label :order_location_id, 'Ordered At' %>
			<%= select_tag :order_location_id, options_from_collection_for_select(@locations, 'id', 'name', @selected_order_location_id), { prompt: 'All Locations' } %>
		</div>
		<div>
		<%= label :pickup_location_id, 'Pickup At' %>
		<%= select_tag :pickup_location_id, options_from_collection_for_select(@locations, 'id', 'name', @selected_pickup_location_id), { prompt: 'All Locations' } %>
 		</div>
		<div>
	    <%= label :user_id, 'Order Taken By' %>
	    <%= select_tag :user_id, option_groups_from_collection_for_select(@locations, :staff, :name, :id, :username, @selected_user_id), { prompt: 'Choose Staff Member' } %>
		</div>
	 </div>
	 <div>
	 	<%= submit_tag "Filter List", class: 'action' %>
	 </div>
	

	
<% end %>

app/views/orders/_subnav.html.erb
<nav class="subnav">
	<%= link_to "Daily Orders", :daily_orders %>
	<%= link_to "Daily Messages", :daily_messages %>
</nav>

app/views/orders/daily_messages.html.erb
<h1>Daily Messages</h1>

<div class='actions'>
	<%= link_to 'Previous Day', daily_messages_path(date: @date - 1.day), class: 'action' %>
	<%= link_to 'Next Day', daily_messages_path(date: @date + 1.day), class: 'action' %>
</div>
<table>
	<%= content_tag(:h2, @date.strftime('%d/%m')) %>
	<tr>
		<th>Message</th>
		<th>Photo</th>
		<th colspan="2"></th>
	</tr>

<%= render partial: 'orders/messages/order', collection: @orders %>
</table>

app/views/orders/daily_orders.html.erb
<h1>Daily Orders</h1>

<div class='actions'>
	<%= link_to 'Previous Day', daily_orders_path(date: @date - 1.day), class: 'action' %>
	<%= link_to 'Next Day', daily_orders_path(date: @date + 1.day), class: 'action' %>
</div>

<table>
	<%= content_tag(:h2, @date.strftime('%d/%m')) %>
	<tr>
		<th>Pickup</th>
		<th>Date</th>
		<th>Time</th>
		<th>Style</th>
		<th>Size</th>
		<th>Message</th>
		<th>Notes</th>
		<th colspan="2"></th>
	</tr>

	<%= render @orders %>
</table>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>
 
<%= render 'form' %>

app/views/orders/index.html.erb
<%= render 'search_bar' %>

<div id='content'>

	

<h1>Orders</h1>

<table>
	<tr>
		<th>Pickup</th>
		<th>Date</th>
		<th>Time</th>
		<th>Style</th>
		<th>Size</th>
		<th>Message</th>
		<th>Notes</th>
		<th colspan="2"></th>
	</tr>

	<%= render @orders %>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

app/views/orders/search.html.erb
<%= render 'search_bar' %>

<div id='content'>

	

<h1>Search Results</h1>

<table>
	<tr>
		<th>Pickup</th>
		<th>Date</th>
		<th>Time</th>
		<th>Style</th>
		<th>Size</th>
		<th>Message</th>
		<th>Notes</th>
		<th colspan="2"></th>
	</tr>

	<%= render partial: @orders %>
</table>

app/views/orders/show.html.erb
<div class='form'>
<div class='actions row'>
  <%= link_to 'Edit', edit_order_path(@order), class: 'action' %>
  <%= cancel_switch(@order) %>
</div>

<div class='statuses row'>
  <%= cancelled?(@order) %>
  <%= not_current_style?(@order) %>
  <%= outstanding_balance?(@order) %>
</div>

<div class='row 1'>
  <div class='column 1'>
    <div>
      Customer Name: <%= @order.customer_name %>
    </div>
    <div>
      Customer Phone: <%= @order.customer_phone %>
    </div>
    <div>
      Ordered By: <%= @order.user.username %>
    </div>
    <div>
      <%= link_to @order.cake_style.name, cake_style_path(@order.cake_style), class: 'action' %>
    </div>
    <div>
      <%= @order.cake_size.name %>
    </div>
  </div>
  <div class='column 2'>
    <div>
      <%= @order.cake_message %>
    </div>
    <div>
      <%= image_tag @order.message_photo.url(:medium) if @order.message_photo? %>
    </div>
    <div>
      Price: <%= @order.price %>
    </div>
    <div>
      Deposit: <%= @order.deposit %>
    </div>
  </div>
  <div class='column 3'>
    <div>
      <%= @order.notes %>
    </div>
    <div>
      <%= image_tag @order.cake_style.style_photo.url(:thumb) if @order.cake_style.style_photo %>
    </div>
  </div>
</div>

<div class='row 2'>
  <div>
    Ordered: 
    <%= link_to @order.order_location.name, location_path(@order.order_location), class: 'action' %>
    <%= @order.order_date.strftime('%d/%m') %>
  </div>
  <div>
    Pickup:
    <%= link_to @order.pickup_location.name, location_path(@order.pickup_location), class: 'action' %>
    <%= @order.pickup_date.strftime('%d/%m') %>
    <%= @order.pickup_time.strftime('%l:%M%p') %>
  </div>
</div>

<div>
<%= render @order.comments %>
</div>

<%= render 'comments/form' %>


</div>