config/routes.rb
Rails.application.routes.draw do

  resources :cake_sizes
  resources :users
  resources :cake_styles do
    collection do
      get 'all'
      get 'current'
    end
  end
  resources :locations
  resources :orders do
  	resources :comments
    collection do
      get 'search'
    end
    member do
      patch 'cancel_switch'
    end
  end
  
  get '/daily_orders', to: 'orders#daily_orders', as: :daily_orders
  get '/daily_messages', to: 'orders#daily_messages', as: :daily_messages
  get '/login', to: 'access#login', as: :login
  post '/attempt_login', to: 'access#attempt_login', as: :attempt_login
  get '/admin_panel', to: 'access#admin_panel', as: :admin_panel
  get '/logout', to: 'access#logout', as: :logout
  root 'access#admin_panel'

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :confirm_logged_in, except: [:login, :attempt_login]

	private
  	def params_date(prefix)
		Date.civil(params[prefix][:year].to_i, params[prefix][:month].to_i, params[prefix][:day].to_i)
	end

  def redirect_back_or_default(default = :orders, options = {})
  redirect_to (request.referer.present? ? :back : default), options
end

	def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to(:controller => 'access', :action => 'login')
      return false
    else
      return true
    end
  end

  def allow_admin
    unless User.find(session[:user_id]).admin
      flash[:notice] = "Please log in as an Admin."
      redirect_back_or_default
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def error_messages_for(object)
		render partial: "application/error_messages", 
			locals: { object: @object}
	end
	
end

app/views/application/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(object.errors.count, "error") %> prohibited this order from being saved:
      </h2>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/application/_main_nav.html.erb
<nav class="main-nav" role=navigation>
	<%= link_to 'CAKES', current_cake_styles_path %>
	<%= link_to 'ORDERS', orders_path %>
	<%= User.find(session[:user_id]).location.name %>
	<%= link_to 'NEW ORDER', new_order_path %>
	<% if User.find(session[:user_id]).admin %>
		<%= link_to 'ADMIN PANEL', :admin_panel %>
	<% else %>
		<%= link_to 'LOGOUT', :logout %>
	<% end %>
</nav>